spring:
  redis:
    database: 0
    host: 59.110.23.2
    port: 6379
    password: Pass@word1
    #连接池
    lettuce:
      pool:
        max-wait: 1
        max-idle: 8
        max-active: 8
      shutdown-timeout: 300ms


